server:
  port: 1986

bot:
  name: the_tumbochka_bot
  token: 7182070359:AAFMJbWIWfp_NgQcpWZjX_zWW0aMb2Lt28o

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: vlat
    password: 31415926Zdec
