server:
  port: 2012

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bychkovskiyvlad05@gmail.com
    password: jrin qcgp xsnr qleh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

service:
  activation:
    uri: http://192.168.43.86:2005/user/activation?id={id}